#spring.datasource.url=jdbc:mysql://localhost:3306/GoGood
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.username=gogood_user-db
#spring.datasource.password=vaideboa
#spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql = true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.226.122.160:3306:3306/GoGood
    username: root
    password: dEED163g3bDBfeGeHaHD1EGGha6bC46g
  flyway:
    baseline-on-migrate: false
  jackson:
    serialization:
      write-date-keys-as-timestamps: true
  redis:
    lettuce:
      pool:
        max-active: 8 # Número máximo de conexões ativas
        max-idle: 8 # Número máximo de conexões ociosas
        min-idle: 0 # Número mínimo de conexões ociosas
        max-wait: -1ms # Tempo máximo de espera por uma conexão, -1 significa sem limite
  data:
    redis:
      port: 6379
      host: 52.226.122.160
      ssl:
        enabled: false
