spring:
  main:
    allow-circular-references: true
  cache:
    redis:
      ttl:
        rotasCompartilhadas: 300
        rotas: 300
  datasource:
    hikari:
      minimum-idle: 5
      validation-timeout: 5000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      keepalive-time: 300000
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      write-date-keys-as-timestamps: true
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      password: ${REDIS_PASSWORD}
      timeout: -1

    mongodb:
      repositories:
        type: imperative
      uri: ${MONGODB_URL}
      database: ${MONGODB_DATABASE}
server:
  port: 5050

jwt:
  validity: 3600000
  secret: ${JWT_SECRET}
