#logging:
#  level:
#    org:
#      springframework:
#        data:
#          r2dbc: DEBUG
#    io:
#      r2dbc: DEBUG
#    reactor: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  cache:
    type: redis
  jackson:
    serialization:
      write-date-keys-as-timestamps: true
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
