#logging:
#  level:
#    org:
#      springframework:
#        data:
#          r2dbc: DEBUG
#    io:
#      r2dbc: DEBUG
#    reactor: DEBUG

spring:
  r2dbc:
    pool:
      initial-size: 30
      max-size: 50
    url: r2dbc:mysql://52.226.122.160:3306/GoGood
    username: root
    password: Root@123
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://52.226.122.160:3306/GoGood
#    username: root
#    password: Root@123


  cache:
    type: redis
  jackson:
    serialization:
      write-date-keys-as-timestamps: true
  data:
    redis:
      port: 6379
      host: 52.226.122.160
      connect-timeout: 10000
      lettuce:
        pool:
          max-active: -1
          max-idle: -1
          min-idle: 4
          max-wait: 14000
        shutdown-timeout: 60000
    mongodb:
      port: 27017
      username: gogood-root
      host: 52.226.122.160
      password: gogood24
      database: gogood
      authentication-database: admin
  main:
    allow-circular-references: true
  mvc:
    async:
      request-timeout: 100000

