#logging:
#  level:
#    org:
#      springframework:
#        data:
#          r2dbc: DEBUG
#    io:
#      r2dbc: DEBUG
#    reactor: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: redis
  jackson:
    serialization:
      write-date-keys-as-timestamps: true
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
      lettuce:
        pool:
          time-between-eviction-runs: 60000 # 1 minuto em milissegundos
          max-active: 8
          max-idle: 8
          min-idle: 0
      password: ${REDIS_PASSWORD}

    mongodb:
      repositories:
        type: imperative
      uri: ${MONGODB_URL}
      database: ${MONGODB_DATABASE}
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
            repository:
              Query: DEBUG
