#logging:
#  level:
#    org:
#      springframework:
#        data:
#          r2dbc: DEBUG
#    io:
#      r2dbc: DEBUG
#    reactor: DEBUG


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: redis
  jackson:
    serialization:
      write-date-keys-as-timestamps: true
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          max-wait: 1000ms
      timeout: 120000

    mongodb:
      repositories:
        type: imperative
      uri: ${MONGODB_URL}
      database: ${MONGODB_DATABASE}
