name: Java CI with Maven and Auto Tagging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        R2DBC_URL: ${{ secrets.R2DBC_URL }}
        R2DBC_USERNAME: ${{ secrets.R2DBC_USERNAME }}
        R2DBC_PASSWORD: ${{ secrets.R2DBC_PASSWORD }}
        JDBC_URL: ${{ secrets.JDBC_URL }}
        JDBC_USERNAME: ${{ secrets.JDBC_USERNAME }}
        JDBC_PASSWORD: ${{ secrets.JDBC_PASSWORD }}
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
        MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
        SWAGGER_URL: ${{ secrets.SWAGGER_URL }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        initial_version: '1.0.0'
        release_branches: main

    - name: Upload Artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: target/*.jar

  CD:
    needs: [CI]
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: application
        path: target/
    
    - name: Verificar arquivos no diretório de origem
      run: ls -la /home/ubuntu/java-app/target

    - name: Transferir JAR sem tar
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 10.0.0.156
        username: ubuntu
        key_path: "/home/ubuntu/.ssh/gogoodkey.pem"
        port: 22
        source: "/home/ubuntu/java-app/target/gogood-api-0.0.1-SNAPSHOT.jar"
        target: "/home/ubuntu/gogood/"
        overwrite: true  # Permite sobrescrever arquivos no destino
        rm: false  # Não remove arquivos após a transferência
